# Global Pooling

In Pooling layers that we discussed before, after layer we need Fully connected or Dense layer where each neuron is connected to every neuron in preceding layer. Global Pooling layers can produce one-dimensional single value that can be executed in softmax without Dense layer.

## Global max pooling

In [4]:
import numpy as np
import tensorflow as tf

matrix = np.array([[5.,6.,1.,4.],
                   [6.,3.,9.,2.],
                   [5.,0.,2.,4.],
                   [7.,0.,2.,0.]]).reshape(1,2,2,4)
print(matrix)

global_max_pooling=tf.keras.layers.GlobalMaxPool2D()
global_max_pooled_matrix=global_max_pooling(matrix)
print(global_max_pooled_matrix)

[[[[5. 6. 1. 4.]
   [6. 3. 9. 2.]]

  [[5. 0. 2. 4.]
   [7. 0. 2. 0.]]]]
tf.Tensor([[7. 6. 9. 4.]], shape=(1, 4), dtype=float32)


## Global average pooling

In [5]:
global_average_pooling=tf.keras.layers.GlobalAveragePooling2D()
global_average_pooled_matrix=global_average_pooling(matrix)
print(global_average_pooled_matrix)

tf.Tensor([[5.75 2.25 3.5  2.5 ]], shape=(1, 4), dtype=float32)
