# Pooling

<p><b>Pooling layers</b> are part of Convolutional Neural Networks (CNN). While Convolutional layers are responsible for identifying features in images, Pooling layers play a role in summarizing the features acquired by CNNs. Their primary objective is to progressively reduce the spatial dimensions of the representation, thereby reducing the volume of parameters and computational load within the network. For example, if we take image of size 256x256 and kernel of polling 2x2 then after pooling we will get image of size 128x128. This will reduce the spatial dimensions (width and height) of the input volume while retaining  important features.
<p>There are many types of pooling layers, such Max Pooling, Min Pooling, Average Pooling, Stochastic Polling and etc. but we will discuss only most commonly used types.

## Max pooling

Max Pooling is mainly used type of pooling layer. It retains only the highest value from each kernel matrices and discards the other values.
This means that max pooling will take the sharpest pixels from original image and reduced image consequently will be sharper than original.

QUIZ!
What will be output of this matrix after Max Polling layer with kernel 2x2?
[[9 2 8 8]
 [4 0 8 6]
 [7 6 7 7]
 [8 7 4 7]]

In [16]:
import numpy as np

matrix = np.random.randint(0, 10, size=(4, 4))

print(matrix)

[[1 6 7 4]
 [3 4 2 3]
 [2 6 3 9]
 [3 3 0 1]]


In [14]:
import tensorflow as tf

matrix = matrix.reshape(1,4,4,1)

max_pooling=tf.keras.layers.MaxPool2D(pool_size=2,strides=2)
max_pooled_matrix=max_pooling(matrix)
print(max_pooled_matrix.shape)
print(tf.squeeze(max_pooled_matrix))

(1, 2, 2, 1)
tf.Tensor(
[[6 9]
 [9 8]], shape=(2, 2), dtype=int32)


## Average pooling

QUIZ!
What will be output of this matrix after Average Polling layer with kernel 2x2?
[[0 2 8 3]
 [4 2 4 3]
 [2 1 5 2]
 [8 3 6 8]]

In [27]:
# matrix = matrix.reshape(1,4,4,1)
matrix = np.array([[3.,2.,0.,0.],
                   [0.,7.,1.,3.],
                   [5.,2.,3.,0.],
                   [0.,9.,2.,3.]]).reshape(1,4,4,1)

average_pooling = tf.keras.layers.AveragePooling2D(pool_size=2, strides=2)
average_pooled_matrix = average_pooling(matrix)
print(average_pooled_matrix.shape)
print(tf.squeeze(average_pooled_matrix))

(1, 2, 2, 1)
tf.Tensor(
[[3. 1.]
 [4. 2.]], shape=(2, 2), dtype=float32)


![SegmentLocal](pooling.gif "Pooling layers")

## Global max pooling

## Global average pooling